### ISSUE TITLE
Item Listing not getting updated when the update button is clicked

### ISSUE THREAD

**Issue by vsingh2201** [vsingh2201/2311-Project-Team1#12]
**Problem Report Number:** 1
**Reported by:** Vikramjeet Singh
**Date Reported**: 2024/03/24
**Program (or Component) name:** Farmer Landing Page
**Release number**: NA
**Version (build) identifier**: NA
**Configuration(s):** Build and Run the project using Gradle wrapper script
**Report Type:** Coding, Exception Management fault
**Can reproduce:** Sometimes
**Severity:** HIGH
**Priority:** HIGH
**Problem summary:** A machine or a produce listing not getting updated when the update button is clicked.
**Key words:**
Null-Pointer Exception, Update button Event-Handler, ItemController, ItemService
**Problem description and how to reproduce it**
<img width="939" alt="Screenshot 2024-03-24 at 9 58 04 PM" src="https://github.com/vsingh2201/2311-Project-Team1/assets/70337807/a632886a-1957-48f3-ad65-59041ae33da2">

Login to the app with username = “johndoes” and password=”password123”. On the Farmer Landing Page, add a new item. Scroll to the newly added item and click on the update button. The Farmers Hub-Edit item page will be displayed. Enter the new product details and click on the update button. In this case, the update button didn’t work and the event handler for update button throws a null pointer exception.
**Suggested fix**
Event Handler for update button throws a null pointer exception under certain conditions. Handle null pointer exception.
**Status:** Open
**Resolution:** Pending
**Resolved by:**

**Comment by Eromosele-Dexter** [comment]
This issue has been fixed
