### ISSUE TITLE
Duplicate Item is added to the list when the Update button is clicked

### ISSUE THREAD

**Issue by vsingh2201** [vsingh2201/2311-Project-Team1#13]
**Problem Report Number:** 2
**Reported by:** Vikramjeet Singh
**Date Reported:** 2024/03/24
**Program (or Component) name:** Farmer Landing Page
**Release number:** NA
**Version (build) identifier:** NA
**Configuration(s):** Build and Run the project using Gradle wrapper script
**Report Type:** Coding
**Can reproduce:** Sometimes
**Severity:** LOW
**Priority:** HIGH
**Problem summary:** When an existing item in the list is updated, a duplicate item is added to the list and the existing item doesn’t get updated.
**Key words:**
Duplicate item, ItemController, ItemService, Update button Event Handler
**Problem description and how to reproduce it:**
<img width="931" alt="Screenshot 2024-03-24 at 10 07 31 PM" src="https://github.com/vsingh2201/2311-Project-Team1/assets/70337807/8cd8f8cb-8883-4c49-b951-e818766e8cb8">

Login to the app with username = “johndoes” and password=”password123”. On the Farmer Landing Page, add a new item. Scroll to the newly added item and click on the update button. The Farmers Hub-Edit item page will be displayed. Enter the new product details and click on the update button. In this case, the Fertilizer listing didn’t get updated and a new duplicate Fertilizer listing is added after clicking the update button.
**Suggested fix:**
Use the “debug’ Gradle task for debugging. Fix Event Handler for update button on Farmers Hub-Edit Item page
**Status:** Open
**Resolution:** Pending
**Resolved by:**

**Comment by Eromosele-Dexter** [comment]
This issue has been fixed
